version: "3"
## added REDIS_HOST=redis to Dockerfile
services:
  front:
    image: front
    ports:
      - 5000:5000
    build: .
  back:
    image: back
    ports:
      - 8080:8080
    build: .
    environment:
      - POSTGRES_HOST = postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    build: .
